# Generated by Django 4.0 on 2024-03-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to='post/imgs/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='post 78', max_length=128, null=True),
        ),
    ]
